export type DietaryTag = "vegan" | "gf" | "spicy";
export interface MenuItem { name: string; description: string; price: string; emoji: string; image?: string; tags: DietaryTag[]; badge?: string; comingSoon?: boolean; }
export interface MenuCategory { id: string; label: string; emoji: string; subtitle?: string; items: MenuItem[]; }

export const menuCategories: MenuCategory[] = [
  { id: "lunch-special", label: "Lunch Special", emoji: "🌞", subtitle: "Mon – Sat · 11 AM – 2 PM · Pickup only", items: [
    { name: "K-Lunch Box — Combo 1", description: "K-pop Chicken & Gimbap with Yam & Salad", price: "$9.99", emoji: "🍱", image: "/images/menu/lunch-special/klunch-box-combo1.png", tags: [], badge: "🌞 Lunch Deal" },
    { name: "K-Lunch Box — Combo 2", description: "K-pop Chicken & Fried Rice with Chicken Dumplings & Salad", price: "$9.99", emoji: "🍱", image: "/images/menu/lunch-special/klunch-box-combo2.png", tags: [], badge: "🌞 Lunch Deal" },
    { name: "K-Lunch Box — Combo 3", description: "K-pop Chicken & Japchae Noodle with Yam & Salad", price: "$9.99", emoji: "🍱", image: "/images/menu/lunch-special/klunch-box-combo3.png", tags: [], badge: "🌞 Lunch Deal" },
    { name: "K-Lunch Box — Combo 4", description: "Bulgogi Bibimbap with sweet K-spicy gochujang sauce", price: "$9.99", emoji: "🍱", image: "/images/menu/lunch-special/klunch-box-combo4.png", tags: [], badge: "🌞 Lunch Deal" },
    { name: "K-Lunch Box — Combo 5 (Vegan)", description: "Vegan Bibimbap with K-spicy gochujang sauce", price: "$9.99", emoji: "🍱", image: "/images/menu/lunch-special/klunch-box-combo5.png", tags: ["vegan"], badge: "🌞 Lunch Deal" },
    { name: "K-Lunch Rice Bowl — Bulgogi", description: "Bulgogi Bibimbap rice bowl", price: "$9.99", emoji: "🥣", image: "/images/menu/lunch-special/klunch-bowl-bulgogi.png", tags: [], badge: "🌞 Lunch Deal" },
    { name: "K-Lunch Rice Bowl — Vegan", description: "Vegan Bibimbap rice bowl", price: "$9.99", emoji: "🥣", image: "/images/menu/lunch-special/klunch-bowl-vegan.png", tags: ["vegan"], badge: "🌞 Lunch Deal" },
    { name: "K-Pop Chicken", description: "10–12 boneless pieces with sweet chilli sauce", price: "$10.99", emoji: "🍗", image: "/images/menu/lunch-special/kpop-chicken-lunch.png", tags: [], badge: "🌞 Lunch Deal" },
    { name: "KFC Wings (6 pcs)", description: "Crispy wings with sweet chilli sauce", price: "$10.99", emoji: "🍗", image: "/images/menu/lunch-special/kfc-wings-lunch.png", tags: [], badge: "🌞 Lunch Deal" },
    { name: "K-Spicy Chicken Deopbap", description: "Dakgalbi — spicy chicken over rice", price: "$10.99", emoji: "🥣", image: "/images/menu/lunch-special/kspicy-chicken-deopbap.png", tags: ["spicy"], badge: "🌞 Lunch Deal" },
    { name: "K-Sweet Chilli Pork Deopbap", description: "Jeyuk Bokkeum — sweet chilli pork over rice", price: "$10.99", emoji: "🥣", image: "/images/menu/lunch-special/ksweet-pork-deopbap.png", tags: [], badge: "🌞 Lunch Deal" },
  ]},
  { id: "appetizers", label: "Appetizers", emoji: "🥗", items: [
    { name: "Edamame", description: "Steamed salted edamame", price: "$7.99", emoji: "🫛", image: "/images/menu/appetizers/edamame.png", tags: ["vegan","gf"] },
    { name: "Crispy Tofu", description: "Lightly fried tofu with dipping sauce", price: "$8.99", emoji: "🟨", image: "/images/menu/appetizers/crispy-tofu.png", tags: ["vegan"] },
    { name: "Chicken Dumplings", description: "Pan-fried chicken dumplings", price: "$8.99", emoji: "🥟", image: "/images/menu/appetizers/chicken-dumplings.png", tags: [] },
    { name: "Vegetable Dumplings", description: "Pan-fried vegetable dumplings", price: "$8.99", emoji: "🥟", image: "/images/menu/appetizers/veggie-dumplings.png", tags: ["vegan"] },
  ]},
  { id: "gimbap", label: "Gimbap", emoji: "🌯", subtitle: "8–10 pcs · housemade sauces", items: [
    { name: "Original", description: "Carrot, crab meat, spam/ham, egg, cucumber, pickled daikon", price: "$9.99", emoji: "🌯", image: "/images/menu/gimbap/original-gimbap.png", tags: [] },
    { name: "Vegan", description: "Carrot, cucumber, red cabbage, red sweet pepper, vegan spicy mayo", price: "$9.99", emoji: "🌯", image: "/images/menu/gimbap/vegan-gimbap.png", tags: ["vegan"] },
    { name: "California Roll", description: "Avocado, cucumber, crab meat, carrot, Rice N Rolls spicy mayo", price: "$10.99", emoji: "🌯", image: "/images/menu/gimbap/california-roll.png", tags: [] },
    { name: "Crispy Veggie Roll", description: "Crispy onion, carrot, red sweet pepper, yam, cucumber", price: "$10.99", emoji: "🌯", image: "/images/menu/gimbap/crispy-veggie-roll.png", tags: ["vegan"] },
    { name: "Yam Avo Roll", description: "Crispy yam, red sweet pepper, avocado", price: "$10.99", emoji: "🌯", image: "/images/menu/gimbap/yam-avo-roll.png", tags: ["vegan"] },
    { name: "K-Spicy Chicken", description: "K-spicy chicken, carrot, lettuce, cabbage", price: "$11.99", emoji: "🌯", image: "/images/menu/gimbap/kspicy-chicken-gimbap.png", tags: ["spicy"], badge: "🌶️ Spicy" },
    { name: "Beef Bulgogi", description: "Beef bulgogi, carrot, lettuce", price: "$11.99", emoji: "🌯", image: "/images/menu/gimbap/beef-bulgogi-gimbap.png", tags: [], badge: "⭐ Best Seller" },
    { name: "Crispy Chicken", description: "Crispy chicken tender, sweet red pepper, cucumber, teriyaki mayo", price: "$11.99", emoji: "🌯", image: "/images/menu/gimbap/crispy-chicken-gimbap.png", tags: [] },
    { name: "Tuna", description: "Canned tuna, carrot, cucumber, lettuce, egg, chilli pepper, crab meat", price: "$11.99", emoji: "🌯", image: "/images/menu/gimbap/tuna-gimbap.png", tags: [] },
    { name: "Yam (6 pcs)", description: "Crispy yam rolls", price: "$6.99", emoji: "🌯", image: "/images/menu/gimbap/yam-roll.png", tags: ["vegan"] },
    { name: "Avocado (6 pcs)", description: "Fresh avocado rolls", price: "$6.99", emoji: "🥑", image: "/images/menu/gimbap/avocado-roll.png", tags: ["vegan"] },
    { name: "Fried Tofu Stuffed Rice (3 pcs)", description: "Rice, carrots, fried tofu (yubuchobap)", price: "$6.99", emoji: "🍱", image: "/images/menu/gimbap/fried-tofu-rice.png", tags: ["vegan"] },
  ]},
  { id: "bibimbap", label: "Bibimbap", emoji: "🍚", subtitle: "Korean rice bowl", items: [
    { name: "Beef Bulgogi Bibimbap", description: "Rice, carrots, cabbage, ground beef bulgogi — gochujang or sesame soya", price: "$15.99", emoji: "🍚", image: "/images/menu/bibimbap/beef-bulgogi-bibimbap.png", tags: [], badge: "❤️ Fan Fave" },
    { name: "Chicken Bibimbap", description: "Rice, carrots, cabbage, seasoned chicken — gochujang or sesame soya", price: "$15.99", emoji: "🍚", image: "/images/menu/bibimbap/chicken-bibimbap.png", tags: [] },
    { name: "Vegan Bibimbap", description: "Rice, carrots, seasonal herbs, cabbage, mushroom", price: "$15.99", emoji: "🍚", image: "/images/menu/bibimbap/vegan-bibimbap.png", tags: ["vegan","gf"] },
  ]},
  { id: "fried-rice", label: "Fried Rice", emoji: "🍳", items: [
    { name: "Chicken Fried Rice", description: "Rice, peas, carrot, green bean, green onion, chicken", price: "$13.99", emoji: "🍳", image: "/images/menu/fried-rice/chicken-fried-rice.png", tags: [] },
    { name: "Veggie Fried Rice", description: "Rice, peas, carrot, green bean, green onion, mushroom", price: "$13.99", emoji: "🍳", image: "/images/menu/fried-rice/veggie-fried-rice.png", tags: ["vegan"] },
    { name: "Beef Fried Rice", description: "Rice, peas, carrot, green bean, green onion, beef", price: "$13.99", emoji: "🍳", image: "/images/menu/fried-rice/beef-fried-rice.png", tags: [] },
    { name: "Kimchi Fried Rice", description: "Rice, green onion, kimchi", price: "$13.99", emoji: "🍳", image: "/images/menu/fried-rice/kimchi-fried-rice.png", tags: ["spicy"] },
  ]},
  { id: "signature", label: "Signature", emoji: "⭐", subtitle: "House specialties", items: [
    { name: "K-Pop Chicken", description: "Crispy boneless chicken thigh — sweet & spicy K-pop or honey soya sauce, with pickles", price: "$25.99 / Half $13.99", emoji: "🍗", image: "/images/menu/signature/kpop-chicken-full.png", tags: ["spicy"], badge: "🔥 House Special" },
    { name: "K.F.C. Wings (6 pcs)", description: "Sweet & spicy K-pop sauce or mild soya honey", price: "$10.99", emoji: "🍗", image: "/images/menu/signature/kfc-wings.png", tags: [] },
    { name: "K-Spicy Chicken Set", description: "Rice, chicken, rice cake with Korean spicy sauce, coleslaw", price: "$18.99", emoji: "🌶️", image: "/images/menu/signature/kspicy-chicken-set.png", tags: ["spicy"] },
    { name: "K-Spicy Tofu Set", description: "Rice, tofu, rice cake with Korean spicy sauce, coleslaw", price: "$15.99", emoji: "🌶️", image: "/images/menu/signature/kspicy-tofu-set.png", tags: ["vegan","spicy"] },
    { name: "L.A. Galbi Set", description: "Three strips Korean grilled beef short rib, rice, seasonal salad", price: "$27.99", emoji: "🥩", image: "/images/menu/signature/la-galbi-set.png", tags: [], badge: "💎 Premium" },
    { name: "Beef Bulgogi Set", description: "Thin sliced sweet soy beef, rice, coleslaw", price: "$18.99", emoji: "🥩", image: "/images/menu/signature/beef-bulgogi-set.png", tags: [] },
    { name: "K-Spicy Pork Set", description: "Sliced pork with K-spicy sauce, onion, green onion, cabbage, rice", price: "$18.99", emoji: "🐷", image: "/images/menu/signature/kspicy-pork-set.png", tags: ["spicy"] },
    { name: "Japchae", description: "Glass noodles, carrot, peppers, mushroom — add chicken or bulgogi +$2", price: "$14.99", emoji: "🍜", image: "/images/menu/signature/japchae.png", tags: ["vegan","gf"], badge: "🌿 Vegan · GF" },
    { name: "Donkatsu", description: "Rice, crispy pork cutlet, coleslaw with house dressing", price: "$16.99", emoji: "🍱", image: "/images/menu/signature/donkatsu.png", tags: [] },
    { name: "Tofu-Katsu", description: "Rice, crispy tofu cutlet, coleslaw with house dressing", price: "$15.99", emoji: "🍱", image: "/images/menu/signature/tofu-katsu.png", tags: ["vegan"] },
    { name: "Tteokbokki", description: "Rice cake, fish cake with spicy & sweet gochujang sauce", price: "$13.99", emoji: "🍢", image: "/images/menu/signature/tteokbokki.png", tags: ["spicy"] },
    { name: "Veggie Tteokbokki", description: "Vegetarian tteokbokki", price: "$12.99", emoji: "🍢", image: "/images/menu/signature/veggie-tteokbokki.png", tags: ["vegan","spicy"] },
    { name: "K-Dinner Box Set", description: "Bulgogi or K-spicy chicken, rice, fresh veggies, K-samjang sauce", price: "$24.99", emoji: "🥡", image: "/images/menu/signature/kdinner-box.png", tags: [] },
  ]},
  { id: "deopbap", label: "Deopbap", emoji: "🥣", subtitle: "Topped rice · $14.99 · includes miso soup", items: [
    { name: "K-Spicy Chicken Deopbap", description: "Chicken, onion, carrot, cabbage, lettuce, k-spicy sauce, sesame seeds", price: "$14.99", emoji: "🥣", image: "/images/menu/deopbap/kspicy-chicken-deopbap-main.png", tags: ["spicy"] },
    { name: "Mushroom with Tofu Deopbap", description: "Mushroom, tofu, onion, green onion, sesame seeds", price: "$14.99", emoji: "🥣", image: "/images/menu/deopbap/mushroom-tofu-deopbap.png", tags: ["vegan"] },
    { name: "Sweet Chilli Pork Deopbap", description: "Pork, carrot, onion, cabbage, sweet chilli sauce, sesame seeds", price: "$14.99", emoji: "🥣", image: "/images/menu/deopbap/sweet-chilli-pork-deopbap.png", tags: [] },
  ]},
  { id: "dinner-special", label: "Dinner Special", emoji: "🌙", subtitle: "3 set choices · $14.99 each", items: [
    { name: "Dinner Set A — Pork", description: "Donkatsu, sweet chilli pork, chicken dumplings & rice", price: "$14.99", emoji: "🍱", image: "/images/menu/dinner-special/dinner-set-a.png", tags: [], badge: "🌙 Dinner Deal" },
    { name: "Dinner Set B — Chicken", description: "K-pop chicken, K-spicy chicken, chicken dumplings & rice", price: "$14.99", emoji: "🍱", image: "/images/menu/dinner-special/dinner-set-b.png", tags: [], badge: "🌙 Dinner Deal" },
    { name: "Dinner Set C — Veggie", description: "Crispy tofu, veggie dumplings, yam & sweet pumpkin tempura, rice", price: "$14.99", emoji: "🍱", image: "/images/menu/dinner-special/dinner-set-c.png", tags: ["vegan"], badge: "🌙 Dinner Deal" },
  ]},
  { id: "platters", label: "Platters", emoji: "🎊", subtitle: "Great for groups!", items: [
    { name: "Rice N Rolls Platter", description: "38 pcs — original, tuna, bulgogi gimbap + California roll — serves 3–4", price: "$42.99", emoji: "🎊", image: "/images/menu/platters/rnr-platter.png", tags: [] },
    { name: "Vegan Platter (Medium)", description: "38 pcs dairy & egg-free — serves 3–4", price: "$42.99", emoji: "🌿", image: "/images/menu/platters/vegan-platter-med.png", tags: ["vegan"] },
    { name: "Vegan Platter (Large)", description: "56 pcs dairy & egg-free — serves 5–6", price: "$69.99", emoji: "🌿", image: "/images/menu/platters/vegan-platter-lg.png", tags: ["vegan"] },
    { name: "K-Family Combo A", description: "KFC wings, K-pop chicken, gimbap (10 pcs), corn cheese, coleslaw, chips", price: "$45.99", emoji: "🎉", image: "/images/menu/platters/kfamily-combo-a.png", tags: [], badge: "👨‍👩‍👧 Family Deal" },
    { name: "K-Family Combo B (Veggie)", description: "Japchae, vegan crispy tofu set, veggie dumplings (10 pcs), avo + yam rolls", price: "$48.99", emoji: "🎉", image: "/images/menu/platters/kfamily-combo-b.png", tags: ["vegan"], badge: "👨‍👩‍👧 Family Deal" },
  ]},
  { id: "coming-soon", label: "Coming Soon", emoji: "🔜", items: [
    { name: "Kimchi Stew", description: "Traditional Korean kimchi jigae", price: "Soon!", emoji: "🍲", image: "/images/menu/coming-soon/kimchi-stew.png", tags: [], comingSoon: true },
    { name: "Gamjatang", description: "Korean pork bone stew", price: "Soon!", emoji: "🍲", image: "/images/menu/coming-soon/gamjatang.png", tags: [], comingSoon: true },
    { name: "Sundubu", description: "Korean soft tofu stew", price: "Soon!", emoji: "🍲", image: "/images/menu/coming-soon/sundubu.png", tags: ["vegan"], comingSoon: true },
  ]},
];
